import type { Metadata } from 'next'
import { Poppins, Inter, Manrope } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  subsets: ['latin'], 
  variable: "--font-poppins",
  weight: ['100', '200', '300', '400', '500']
});

const inter = Inter({
  subsets: ['latin'], 
  variable: "--font-inter",
});

const manrope = Manrope({
  subsets: ['latin'], 
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: 'Byte Forge',
  description: 'Generated by theweekendcoders.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${manrope.className} bg-white mx-auto h-screen sm:max-w-screen-sm md:max-w-screen-md lg:max-w-screen-lg xl:max-w-full`}>{children}</body>
    </html>
  )
}
